#!/bin/sh

uci set luci.main.lang=zh_cn
#设置默认主题
#uci set luci.main.mediaurlbase=/luci-static/bootstrap_mod
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

ln -sf /sbin/ip /usr/bin/ip

# sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
